/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rims/rim1.glb --output src/components/Rim1.js 
Author: jonver87 (https://sketchfab.com/jonver87)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rotiform-ihr-03027fcac92a476aba1a55c1cb148595
Title: Rotiform IHR
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Rim1Model(props) {
  const { nodes, materials } = useGLTF("/models/rims/rim1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Material.001"]}
      />
      <lineSegments
        geometry={nodes.Object_3.geometry}
        material={materials["Material.004"]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material_002.001"]}
      />
      <mesh geometry={nodes.Object_7.geometry} material={materials.bolts} />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.004"]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials["Material.005"]}
      />
    </group>
  );
}

useGLTF.preload("/models/rims/rim1.glb");
