/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rims/rim2.glb --output src/components/Rim2.js 
Author: jonver87 (https://sketchfab.com/jonver87)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vorsteiner-vfe405-f60be022572740e0ace43624f1d5c1ff
Title: Vörsteiner VFE405
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Rim2Model(props) {
  const { nodes, materials } = useGLTF("/models/rims/rim2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["Material.004"]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["None.001"]}
      />
      <mesh geometry={nodes.Object_8.geometry} material={materials.metal} />
    </group>
  );
}

useGLTF.preload("/models/rims/rim2.glb");
