/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rims/rim3.glb --output src/components/Rim3.js 
Author: jonver87 (https://sketchfab.com/jonver87)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vorsteiner-vfe-401-a02b46a04d1b4daeac6e5c7a80bc1808
Title: Vörsteiner VFE 401
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Rim3Model(props) {
  const { nodes, materials } = useGLTF("/models/rims/rim3.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/rims/rim3.glb");
